lesson-5-html
kladweb/kladkevich-markup-home pull request #2
Opened 2022-07-13 19:07 UTC by kladweb

2022-07-17 22:07 UTC, instinct-it-academy requested changes
Добрый вечер, задание на доработку, обратите внимание на комментарии

2022-07-17 22:07 UTC, instinct-it-academy commented on lesson-5-html/task1.html
> +    <br>
лучше просто обернуть контент ниже в <p>

2022-07-17 22:07 UTC, instinct-it-academy commented on lesson-5-html/task2.html
> +    <p1>SO<sub>2</sub> + NAOH = Na<sub>2</sub>SO<sub>3</sub> + H<sub>2</sub>O</p1>
<p1> - не корректный тег, корректный вариант просто <p>

2022-07-17 22:07 UTC, instinct-it-academy commented on lesson-5-html/task3.html
> +    <br>
так же как и в первом задании, лучше было просто обернуть в <p>

2022-07-18 06:48 UTC, kladweb commented
Здравствуйте. Задание доработано. Ошибки во всех файлах урока 5 исправлены. Материал, связанный с ошибками, повторно изучен.
Спасибо.

2022-07-21 22:32 UTC, instinct-it-academy approved these changes
Добрый вечер, принято

2022-07-21 22:32 UTC, merged